export const skillsets = [
  {
    heading: "Languages & Libraries",
    list: [
      "JavaScript",
      "Typescript",
      "React",
      "Vue",
      "HTML",
      "CSS",
      "Git",
      "Vite",
      "Rollup",
      "Webpack",
      "GSAP",
      "SVG",
      "WebSockets",
      "Express",
      "AdonisJS",
      "Ionic",
      "Capacitor",
      "Firebase",
      "Tailwind",
      "Twilio APIs",
      "Pusher",
      "TipTap/ProseMirror",
    ],
  },
  {
    heading: "Knowledge",
    list: [
      "SPA Architecture Design & Developement",
      "CI/CD Methodology",
      "Unit Testing",
      "Integraton/e2e Testing",
      "Web Animation",
      "Responsive Design & Development",
      "Front End Web Architecture",
      "Web Accessibility",
      "Web Perfomance Optimization",
      "Code Optimization",
      "Gitflow Methodology",
      "UI/UX Design",
      "Wireframes, User Flows, Flowcharts",
    ],
  },
  {
    heading: "Tools",
    list: [
      "CLI",
      "NPM",
      "GitHub",
      "Bitbucket",
      "Gitlab",
      "Netlify",
      "VSCode",
      "Prettier",
      "ESLint",
      "Husky",
      "Figma",
      "Photoshop",
      "Illustrator",
    ],
  },
  {
    heading: "Education",
    list: [
      "Self Taught Developer",
      "Interactive Design (Capilano University)",
      "Apple Technical Coordinator",
      "Apple Help Desk Specialist",
      "Apple Server Support Specialist",
    ],
  },
  {
    heading: "Interests",
    list: [
      "Photography",
      "Travel",
      "Music",
      "Food/Cooking",
      "Snowboarding",
      "Scuba Diving",
      "Bush Regeneration",
    ],
  },
];
